# Site settings
title: PlanetO Cartoon Cover Band
email: planeto.cover.band@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Cover Band di sigle di cartoni animati .  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://planeto.band" # the base hostname & protocol for your site
#twitter_username: cespujunk66
facebook_username: PlanetOCartoonCoverBand
facebook_username_tiny: PlanetO 

#youtube_username: cespujunk66
#github_username:  jekyll

# Build settings
markdown: kramdown
